config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams
  resources :tasks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # As suggested in devise installation after running 'rails generate devise:install'
  # NOTE: Ensure you have defined root_url to *something* in your config/routes.rb.
  #       For example:
  root to: 'tasks#index'

  get '/subscribe', to: 'teams#subscribe'
  get '/unsubscribe/:id', to: 'teams#unsubscribe'
  get '/change_status/:id/:direction', to: 'tasks#change_status'

  get '/filter', to: 'tasks#filter'
  get '/filter-reset', to: 'tasks#reset_filter'
  get '/filter-apply', to: 'tasks#apply_filter'

  get '/calendar', to: 'tasks#calendar'
  get '/exams', to: 'tasks#exams'

  get '/user-tasks/:id/edit', to: 'tasks#edit_user', as: 'edit_user_task'
  patch '/user-tasks/:id/update', to: 'tasks#update_user', as: 'update_user_task'
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  include Filterable
  has_many :user_tasks
  has_many :users, through: :user_tasks

  belongs_to :subject
  delegate :color, :name, :team_name, to: :subject, prefix: true

  has_rich_text :description

  has_many_attached :attachments
  has_many :weblinks
  accepts_nested_attributes_for :weblinks, allow_destroy: true

  validates :name, presence: true
  validates :duedate, presence: true

  scope :filter_by_subject, lambda { |subject|
                              subject = '%' if subject.blank?
                              joins(:subject).where('subjects.name ilike ?', subject.to_s)
                            }

  scope :filter_by_team, lambda { |team|
                           team = '%' if team.blank?
                           joins(subject: :team).where('teams.name ilike ?', team.to_s)
                         }

  scope :filter_by_fulltext, lambda { |fulltext|
    fulltext.gsub!(/[^A-Za-z0-9\säöüÄÖÜß]/u, '') unless fulltext.blank? # remove all characters except german letters

    joins("LEFT JOIN action_text_rich_texts ON action_text_rich_texts.record_id = tasks.id  AND record_type = 'Task'")
      .where(
        "tasks.name ilike '%#{fulltext}%' OR
        subjects.name ilike '%#{fulltext}%' OR
        action_text_rich_texts.body ilike '%#{fulltext}%' OR
        teams.name ilike '%#{fulltext}%'"
      )
  }
  scope :filter_by_duedate_min, lambda { |duedate|
    duedate = Date.today - 7 if duedate.blank?
    where('"tasks"."duedate" > ?', duedate.to_s)
  }
  scope :filter_by_duedate_max, ->(duedate) { where('"tasks"."duedate" < ?', duedate.to_s) unless duedate.nil? }

  def worktype_name
    worktype ? 'Together in a group' : 'On your own'
  end

  def groupwork?
    worktype == true
  end

  def formatted_duedate(show_year)
    if show_year
      duedate.strftime('%A, %d.%m.%y %H:%M')
    else
      duedate.strftime('%A, %d.%m. %H:%M')
    end
  end
end

app/controllers/tasks_controller.rb
#!/usr/bin/env ruby
# frozen_string_literal: true

# Controller to handle tasks
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit edit_user update update_user destroy]

  # GET /tasks or /tasks.json
  def index
    session_vars
    calculate_user_tasks
  end

  # GET /filter-reset
  def reset_filter
    redirect_url = params[:redirect].present? ? params[:redirect] : tasks_url
    session[:subject] = nil
    session[:team] = nil
    session[:status] = nil
    session[:fulltext] = nil
    session[:duedate_min] = nil
    session[:duedate_max] = nil

    respond_to do |format|
      format.html { redirect_to redirect_url }
      format.json { head :no_content }
    end
  end

  # GET /filter-apply
  def apply_filter
    redirect_url = params[:redirect].present? ? params[:redirect] : tasks_url
    session_vars(true) # Force setting session vars

    respond_to do |format|
      format.html { redirect_to redirect_url }
      format.json { head :no_content }
    end
  end

  # GET /change_status/1/prev or /change_status/1/next
  def change_status
    user_task_id = params[:id]
    direction = params[:direction]

    user_task = UserTask.find(user_task_id)

    error = false
    redirect_destination = tasks_url

    case direction
    when 'prev'
      user_task.status = user_task.status_prev
    when 'next'
      user_task.status = user_task.status_next
    when 'todo'
      user_task.status = 1
      redirect_destination = user_task.task
    when 'doing'
      user_task.status = 2
      redirect_destination = user_task.task
    when 'done'
      user_task.status = 3
      redirect_destination = user_task.task
    else
      # Wrong direction-parameter
      error = true
    end

    # Ensure other users can not change staus
    error = true if user_task.user_id != current_user.id

    # Ensure User can not change to status 'nostatus'
    error = true if user_task.status_name(user_task.status) == 'nostatus'

    respond_to do |format|
      # Save only if no error!
      if !error && user_task.save
        format.html { redirect_to redirect_destination, notice: 'Task status was successfully changed.' }
      else
        format.html { redirect_to redirect_destination, notice: 'Task status change failed.' }
      end
      format.json { head :no_content }
    end
  end

  def calendar
    session_vars
    calculate_user_tasks
    calculate_exams
  end

  def exams
    session_vars
    calculate_exams
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    redirect_permission_denied unless current_user.task?(@task)
  end

  # GET /tasks/new
  def new
    unless current_user.admin_teams.any?
      respond_to do |format|
        format.html { redirect_to tasks_url, notice: 'Task can only be created when you are team admin.' }
        format.json { head :no_content }
      end
      return
    end

    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    redirect_permission_denied unless current_user.task_admin?(@task)
  end

  # GET /user-tasks/1/edit
  def edit_user
    redirect_permission_denied unless current_user.task?(@task)
  end

  # GET /filter
  def filter; end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        fill_user_tasks(@task)

        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    unless current_user.task_admin?(@task)
      redirect_permission_denied
      return
    end

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user-tasks/1/update
  def update_user
    unless current_user.task?(@task)
      redirect_permission_denied
      return
    end

    user_task = UserTask.find_by(task_id: @task.id, user_id: current_user.id)
    respond_to do |format|
      if user_task.update(user_task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    unless current_user.task_admin?(@task)
      redirect_permission_denied
      return
    end

    delete_from_user_tasks(@task.id)
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(
      :name,
      :subject_id,
      :subject,
      :duedate,
      :worktype,
      :is_exam,
      :description,
      attachments: [],
      weblinks_attributes: %i[
        id
        name
        url
        _destroy
      ]
    )
  end

  def user_task_params
    params.require(:user_task).permit(
      :personal_notes,
      :planned_date
    )
  end

  def fill_user_tasks(task)
    task.subject.team.users.each do |user|
      user_task = UserTask.new

      user_task.user_id = user.id
      user_task.task_id = task.id
      user_task.status = 1

      user_task.save
    end
  end

  def delete_from_user_tasks(task_id)
    UserTask.where(task_id: task_id).destroy_all
  end

  def redirect_permission_denied
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Permission denied.' }
      format.json { head :no_content }
    end
  end

  def session_vars(force = false)
    force ||= params[:force]

    session[:subject] = params[:subject] if !params[:subject].blank? || force
    session[:team] = params[:team] if !params[:team].blank? || force
    session[:status] = params[:status] if !params[:status].blank? || force
    session[:fulltext] = params[:fulltext] if !params[:fulltext].blank? || force
    session[:duedate_min] = params[:duedate_min] unless params[:duedate_min].blank?
    session[:duedate_max] = params[:duedate_max] unless params[:duedate_max].blank?
  end

  def calculate_exams
    @exams = apply_task_filters(
      current_user.tasks.where(is_exam: true).order(:duedate)
    )
  end

  def calculate_user_tasks
    # Filtern nach Status nur WENN
    #   1. KEIN Fulltext-Filter ist ODER
    #   2. spezieller Status-Filter ausgewählt wurde
    user_tasks = if session[:fulltext].blank? || session[:status].present?
                   current_user.user_tasks.filter_by_status(session[:status])
                 else
                   current_user.user_tasks
                 end

    @tasks = apply_task_filters(
      current_user.tasks.where(id: user_tasks.map(&:task_id), is_exam: false)
    )

    # Changing order of results
    @user_tasks = filtered_user_tasks(2) +
                  filtered_user_tasks(1) +
                  filtered_user_tasks(3)
  end

  def apply_task_filters(tasks)
    tasks
      .filter_by_subject(session[:subject])
      .filter_by_team(session[:team])
      .filter_by_fulltext(session[:fulltext])
      .filter_by_duedate_min(session[:duedate_min])
      .filter_by_duedate_max(session[:duedate_max])
  end

  def filtered_user_tasks(status)
    filtered = current_user.user_tasks.where(status: status, task_id: @tasks.map(&:id))
    if status == 3
      filtered.order(updated_at: :desc) # Order DONE tasks so that last changed are on top
    else
      filtered.joins(:task).order(Arel.sql('coalesce(planned_date, tasks.duedate)'))
    end
  end
end

app/views/tasks/_celebrate.html.erb
<div class="pad celebrate">
  <p class="emojis">🥳🎉</p>
  <p class="text">Time to celebrate ...</p>
  <p class="emojis">😎🌴</p>
  <p class="text">... or time to relax!</p>
  <p class="emojis">✅✅✅</p>
  <p class="text">You're done with all your tasks!</p>
</div>

app/views/tasks/_form.html.erb
<div class="pad">
  <%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter task name" %>

    <%= form.label :subject_id %>
    <%= form.grouped_collection_select(:subject_id, current_user.admin_teams, :subjects, :name, :id, :name, include_blank: "--- Select Subject ---") %>

    <%= form.label :duedate %>
    <div>
      <%= form.datetime_select :duedate %>
    </div>

    <%= form.label :worktype, "Work in groups" %>
      <%= form.check_box :worktype %>

    <%= form.label :is_exam, "Exam?" %>
      <%= form.check_box :is_exam %>

    <%= form.label :description %>
    <div class="description-editor">
      <%= form.rich_text_area :description %>
    </div>

    <section class="nesting">
      <h4>Attachments</h4>
      <%= form.file_field :attachments, multiple: true %>
    </section>

    <section class="nesting">
      <h4>Links</h4>
      <%= form.fields_for :weblinks do |weblinks_form| %>
        <%= render 'weblink_fields', f: weblinks_form %>
      <% end %>

      <div class="add-nesting">
        <%= image_tag("icons/icon-add.svg", alt: "add weblink", class: "show-icon") %>
        <%= link_to_add_association 'Add new weblink', form, :weblinks %>
      </div>
    </section>

    <div class="actions">
      <%= form.submit class: "btn hoverable" %>
      <%= link_to 'Cancel', task ? task : tasks_path, class: "btn hoverable" %>
    </div>
  <% end %>
</div>

app/views/tasks/_searchbar.html.erb
<div id="search-bar">
  <div>
    <%= form_tag redirect, method: "get", id: "form-subscribe" do %>
      <%= hidden_field_tag "force", true %> <!-- force setting session filter even if text-field is empty -->
      <%= text_field_tag :fulltext, session[:fulltext], class: "small-padding", placeholder: "Search ..." %>
      <div>
        <%= submit_tag("", class: "btn search") %>
      </div>
      <div>
        <%= link_to "/filter?redirect=" + redirect, class: "btn filter" do end %>
      </div>
    <% end %>
  </div>

  <%
  def status_name(status)
    case status.to_i
    when 1
      'TODO'
    when 2
      'DOING'
    when 3
      'DONE'
    when 4
      'All status'
    else
      status
    end
  end
  %>

  <%
  if session[:subject].present? ||
     session[:team].present? ||
     session[:status].present? ||
     session[:fulltext].present? ||
     session[:duedate_min].present? ||
     session[:duedate_max].present?
     %>
  <div id="active-filters">
    <div>
      <%= image_tag("icons/icon-filter.svg", alt: "Active Filters") %>
      <section>
        <% def show_filter(type, content) %>
          <div class="filter-tag"><strong><%= type %></strong>: <%= content %></div>
        <% end %>
        <%
        show_filter("Text", session[:fulltext]) if session[:fulltext].present?
        show_filter("Team", session[:team]) if session[:team].present?
        show_filter("Subject", session[:subject]) if session[:subject].present?
        show_filter("Status", status_name(session[:status])) if session[:status].present?
        show_filter("Date from", session[:duedate_min]) if session[:duedate_min].present?
        show_filter("Date to", session[:duedate_max]) if session[:duedate_max].present?
        %>
      </section>
    </div>
    <%= link_to "/filter-reset?redirect=" + redirect, class: "btn filter reset" do end %>
  </div>
<% end %>

</div>

app/views/tasks/_weblink_fields.html.erb
<div class="nested-fields">
  <%= link_to_remove_association f, class: "show-icon" do %>
    <%= image_tag("icons/icon-delete.svg", alt: "remove weblink") %>
  <% end %>
  <div class="multiple-fields">
    <%= f.text_field :name, placeholder: "Name", class: "small-padding" %>
    <%= f.text_field :url, placeholder: "URL", class: "small-padding" %>
  </div>
</div>

app/views/tasks/_welcome.html.erb
<div class="welcome">
  <p class="title">Welcome! 👋🏼</p>
  <p class="paragraph">Thank you for using ToDoGether. For getting started you can either create a new team or subscribe to an already existing team.</p>
  <p class="paragraph">For further information about the application please check out our site on <%= link_to "portfolio.fh-salzburg.ac.at", "https://portfolio.fh-salzburg.ac.at/projects/2021-todogether" %>.</p>
  <%= render "teams/subscribe" %>
  <%= label_tag "Create a Team" %>
  <%= link_to "Create", new_team_path, id: "create-team", class: "btn hoverable block" %>
</div>

app/views/tasks/calendar.html.erb
<div class="pad">
  <% subjects = Array.new %>
  <%= render "searchbar", redirect: calendar_path %>
  <br>
  <%= month_calendar do |date| %>
    <%= date.day %>
    <% @user_tasks.select { |user_task| user_task.planned_date == date }.each do |day_user_task| %>
      <% day_task = Task.find(day_user_task.task_id) %>
      <% subjects.push day_task.subject unless subjects.include? day_task.subject %>
      <%= link_to day_task do %>
        <div class="day-task planned" style="background: <%= day_task.subject_color %>;"></div>
      <% end %>
    <% end %>
    <% @tasks.where(:duedate => date.beginning_of_day..date.end_of_day).each do |day_task| %>
      <% subjects.push day_task.subject unless subjects.include? day_task.subject %>
      <%= link_to day_task do %>
        <div class="day-task" style="background: <%= day_task.subject_color %>;"></div>
      <% end %>
    <% end %>
    <% @exams.where(:duedate => date.beginning_of_day..date.end_of_day).each do |day_exam| %>
      <% subjects.push day_exam.subject unless subjects.include? day_exam.subject %>
      <%= link_to day_exam do %>
        <div class="day-task exam" style="border-color: <%= day_exam.subject_color %>;"></div>
      <% end %>
    <% end %>
  <% end %>
  <h3>Subject colors</h3>
  <table class="calendar_legend">
    <% subjects.each do |subject| %>
      <tr>
        <td>
          <div class="day-task" style="background: <%= subject.color %>;"></div>
        </td>
        <td><%= subject.name %></td>
      </tr>
    <% end %>
  </table>
  <h3>Symbols</h3>
  <table class="calendar_legend">
    <tr>
      <td>
        <div class="day-task planned" style="background: black;"></div>
      </td>
      <td>Task: Planned date</td>
    </tr>
    <tr>
      <td>
        <div class="day-task" style="background: black;"></div>
      </td>
      <td>Task: Due date</td>
    </tr>
    <tr>
      <td>
        <div class="day-task exam" style="border-color: black;"></div>
      </td>
      <td>Exam: Date</td>
    </tr>
  </table>
</div>

app/views/tasks/edit.html.erb
<% @page_title = "Edit Task" %>

<%= render 'form', task: @task %>

app/views/tasks/edit_user.html.erb
<% @page_title = "Edit User Task" %>
<% user_task = current_user.user_tasks.find_by(task_id: @task.id) %>

<div class="pad">
  <%= form_with(model: user_task, url: update_user_task_path) do |form| %>
    <% if user_task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user_task.errors.count, "error") %> prohibited this user task from being saved:</h2>

        <ul>
          <% user_task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.label :personal_notes %>
    <span><em>Edit your personal notes for this task here.</em></span>
    <div class="description-editor">
      <%= form.rich_text_area :personal_notes %>
    </div>

    <% if !@task.is_exam %>
      <%= form.label :planned_date %>
      <span><em>This is the day you plan to do this task (optional). If you set it, this date affects the priority of your tasks on the main screen.</em></span>
      <div>
        <%= form.date_field :planned_date, :include_blank => true, :placeholder => "yyyy-mm-dd" %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit "Update", class: "btn hoverable" %>
      <%= link_to 'Cancel', @task, class: "btn hoverable" %>
    </div>
  <% end %>
</div>

app/views/tasks/exams.html.erb
<div class="pad">
  <% if current_user.teams.size == 0 && current_user.tasks.size == 0 %>
    <%= render "welcome" %>
  <% else %>
    <%= render "searchbar", redirect: exams_path %>
    <% if @exams.size == 0 %>
      <p>There are no exams right now.</p>
      <%= link_to "Reset Filters", "/filter-reset?redirect=" + exams_path, class: "btn hoverable block" %>
    <% end %>
  <% end %>
</div>

<% @page_title = "Exams" %>

<% @exams.each do |task|
  %>
<div class="task">
  <div class="btn slide nostatus"></div>
  <section class="task-content">
    <%= link_to task do %>
      <div class="top">
        <div style="color: <%= task.subject_color %>" class="subject"><%= task.subject_name %></div>
      </div>
      <h4><%= task.name %></h4>
      <div class="bottom">
        <div class="icons">
          <% if(task.weblinks.count > 0) %>
            <%= image_tag("icons/icon-weblink.svg", alt: "Weblink(s) available") %>
          <% end %>
          <% if(task.attachments.count > 0) %>
            <%= image_tag("icons/icon-attachment.svg", alt: "Attachment(s) available") %>
          <% end %>
        </div>
        <div class="dates">
          <% one_day = 24 * 60 * 60 %>
          <div class="duedate <%= "urgent" if (task.duedate - one_day) < DateTime.now %> <%= "overdue" if task.duedate < DateTime.now %>"><%= task.formatted_duedate(false) %></div>
        </div>
      </div>
    <% end %>
  </section>
  <div class="btn slide nostatus"></div>
</div>
<% end %>

app/views/tasks/filter.html.erb
<div class="pad">

  <% @page_title = "Filter" %>

  <%= form_with url: filter_apply_path, method: :get do |f| %>

    <%= f.hidden_field "redirect", value: params[:redirect] %>

    <%= f.label :team, "Selected team" %>
    <%= f.select :team, current_user.teams.collect { |t| t.name }, { selected: session[:team], include_blank: 'All teams' }, { class: "small-padding" } %>

    <%= f.label :subject, "Selected subject" %>
    <%= f.select :subject, current_user.subjects.collect { |s| s.name }, { selected: session[:subject], include_blank: 'All subjects'}, { class: "small-padding" } %>

    <%= f.label :status, "Selected status" %>
    <%= f.select :status, [ [ "TODO" , 1 ] , [ "DOING" , 2 ] , [ "DONE" , 3 ] , [ "All status" , 4 ] ], { selected: session[:status], include_blank: 'Default status (only open)'}, { class: "small-padding" } %>

    <%= f.label :duedate_min, "Due date (from / to)" %>
    <div class="filter-duedate">
      <%= f.date_field :duedate_min, value: session[:duedate_min], class: "small-padding" %>
      <%= f.date_field :duedate_max, value: session[:duedate_max], class: "small-padding" %>
    </div>

    <%= f.label :fulltext, "Text filter" %>
    <%= f.text_field :fulltext, value: session[:fulltext], placeholder: "Search name, description, ...", class: "small-padding" %>
    <br>
    <%= f.submit "Apply Filter", class: "btn hoverable" %>
    <%= link_to "Reset Filters", "/filter-reset?redirect=" + params[:redirect], class: "btn hoverable" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="pad">
  <% if current_user.teams.size == 0 && current_user.tasks.size == 0 %>
    <%= render "welcome" %>
  <% else %>
    <%= render "searchbar", redirect: tasks_path %>
    <% if @user_tasks.size == 0 %>
      <% if !current_user.user_tasks.filter_by_status(nil).any? %>
        <%= render "celebrate" %>
      <% else %>
        <p>Filter didn't find any entries.</p>
        <%= link_to "Reset Filters", "/filter-reset?redirect=" + tasks_path, class: "btn hoverable block" %>
      <% end %>
    <% end %>
  <% end %>
</div>

<% @page_title = "Tasks" %>

<% @user_tasks.each do |user_task|
  task = user_task.task
  status_prev = user_task.status_name(user_task.status_prev)
  status_current = user_task.status_name
  status_next = user_task.status_name(user_task.status_next)
  %>
<div class="task">
  <%= link_to '/change_status/' + user_task.id.to_s + "/prev", class: "btn slide left " + status_prev do end %>
  <section class="task-content <%= status_current %>">
    <%= link_to task do %>
      <div class="top">
        <div style="color: <%= task.subject_color %>" class="subject"><%= task.subject_name %></div>
        <button class="btn status <%= status_current %>"><%= status_current %></button>
      </div>
      <h4><%= task.name %></h4>
      <div class="bottom">
        <div class="icons">
          <% if(task.weblinks.count > 0) %>
            <%= image_tag("icons/icon-weblink.svg", alt: "Weblink(s) available") %>
          <% end %>
          <% if(task.groupwork?) %>
            <%= image_tag("icons/icon-group.svg", alt: "Working in a group") %>
          <% end %>
          <% if(task.attachments.count > 0) %>
            <%= image_tag("icons/icon-attachment.svg", alt: "Attachment(s) available") %>
          <% end %>
        </div>
        <div class="dates">
          <% if user_task.planned_date? %>
            <div><%= user_task.formatted_planned_date(false) %>
              <span>(PLAN)</span>
            </div>
          <% end %>
          <% one_day = 24 * 60 * 60 %>
          <div class="duedate <%= "urgent" if (task.duedate - one_day) < DateTime.now %> <%= "overdue" if task.duedate < DateTime.now %>">
            <%= task.formatted_duedate(false) %>
          </div>
        </div>
      </div>
    <% end %>
  </section>
  <%= link_to '/change_status/' + user_task.id.to_s + "/next", class: "btn slide right " + status_next do end %>
</div>
<% end %>

app/views/tasks/new.html.erb
<% @page_title = "Create Task" %>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="pad form">

  <% @page_title = @task.name + (@task.is_exam ? " [Exam]" : " [Task]") %>
  <% user_task = current_user.user_tasks.find_by(task_id: @task.id) %>

  <h4>
    <% if current_user.task_admin?(@task) %>
      <%= link_to edit_task_path(@task) do %><%= image_tag("icons/icon-edit.svg", alt: "edit task") %><% end %>
    <% end %>
    <%= @task.name %>
    <% if current_user.task_admin?(@task) %>
      <%= link_to @task, method: :delete, data: { confirm: 'Are you sure?' } do %><%= image_tag("icons/icon-delete.svg", alt: "delete task") %><% end %>
    <% end %>
  </h4>

  <div>
    <div style="color: <%= @task.subject_color %>" class="subject">
      <%= @task.subject_name %>
    </div>
    <span>in team <strong><%= @task.subject_team_name %></strong></span>
  </div>

  <% if !@task.is_exam %>
    <div>
      <h5>Current status</h5>
      <% status_names = ["todo", "doing", "done"] %>
      <% status_names.each do |status_name| %>
        <% inactive = status_name == user_task.status_name ? "" : " inactive" %>
        <%= link_to '/change_status/' + user_task.id.to_s + "/" + status_name, class: "btn status " + status_name + inactive do status_name end %>
      <% end %>
    </div>
  <% end %>

  <div>
    <h5><%= @task.is_exam ? "Exam Date" : "Due Date" %></h5>
    <%= @task.formatted_duedate(true) %>
  </div>

  <% if !@task.is_exam %>
    <div>
      <h5>Type of assignment</h5>
      <%= @task.worktype_name %>
    </div>
  <% end %>

  <div>
    <h5>Description</h5>
    <%= @task.description %>
  </div>

  <% if(@task.attachments.any?) %>
    <div>
      <h5>Attachments</h5>
      <% @task.attachments.each do |attachment| %>
        <div>
          <%= image_tag("icons/icon-attachment.svg", alt: "Attachment " + attachment.filename.to_s) %>
          <%= link_to attachment.filename.to_s, url_for(attachment), target: "_blank" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if(@task.weblinks.any?) %>
    <div>
      <h5>Links</h5>
      <% @task.weblinks.each do |link| %>
        <div>
          <%= image_tag("icons/icon-weblink.svg", alt: "Weblink to " + link.name) %>
          <%= link_to link.name, link.url, target: "_blank" %>
        </div>
      <% end %>
    </div>
  <% end %>

  <h4>
    <%= link_to edit_user_task_path(@task) do %><%= image_tag("icons/icon-edit.svg", alt: "edit user task notes") %><% end %>
    Personal information
  </h4>

  <% if(user_task.personal_notes?) %>
    <div>
      <h5>Notes</h5>
      <%= user_task.personal_notes %>
    </div>
  <% end %>

  <% if(user_task.planned_date?) %>
    <div>
      <h5>Planned Date</h5>
      <%= user_task.formatted_planned_date(true) %>
    </div>
  <% end %>

  <%= link_to 'Back', @task.is_exam ? exams_path : tasks_path, class: "btn hoverable" %>
</div>