config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams
  resources :tasks
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # As suggested in devise installation after running 'rails generate devise:install'
  # NOTE: Ensure you have defined root_url to *something* in your config/routes.rb.
  #       For example:
  root to: 'tasks#index'

  get '/subscribe', to: 'teams#subscribe'
  get '/unsubscribe/:id', to: 'teams#unsubscribe'
  get '/change_status/:id/:direction', to: 'tasks#change_status'

  get '/filter', to: 'tasks#filter'
  get '/filter-reset', to: 'tasks#reset_filter'
  get '/filter-apply', to: 'tasks#apply_filter'

  get '/calendar', to: 'tasks#calendar'
  get '/exams', to: 'tasks#exams'

  get '/user-tasks/:id/edit', to: 'tasks#edit_user', as: 'edit_user_task'
  patch '/user-tasks/:id/update', to: 'tasks#update_user', as: 'update_user_task'
end

app/views/layouts/_footer.html.erb
<script>
  function toggleMenu() {
    document.getElementById("menu").classList.toggle("hide");
    document.getElementById("menu-open").classList.toggle("hide");
    document.getElementById("menu-close").classList.toggle("hide");
  }
</script>

<footer>
  <div class="title">
    <%= link_to tasks_url do%>
      <%= image_tag("icons/favicon/icon-32x32.png", alt: "ToDoGether") %>
    <% end %>
    <h4 class="bgblue">
      <%= @page_title %>
    </h4>
  </div>
  <div id="menu-open" class="menu-icon">
    <%= image_tag("icons/icon-menu.svg", alt: "Menu-Icon", onclick: "toggleMenu()") %>
  </div>
  <div id="menu-close" class="menu-icon hide">
    <%= image_tag("icons/icon-close-menu.svg", alt: "Menu-Icon", onclick: "toggleMenu()") %>
  </div>
</footer>
<script>
  if(window.innerWidth > 1024) {
    toggleMenu(); // Initially show menu on bigger screens
  }
</script>

app/views/layouts/_menu.html.erb
<div id="menu" class="hide">
  <div class="side-top">
    <%= link_to tasks_path do %>
      <%= image_tag("icons/favicon/icon-128x128.png", alt: "ToDoGether") %>
      <h1 class="bgblue">ToDoGether</h1>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>
  </div>
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to "Teams", teams_path, class: "btn hoverable block" %>
        </li>
        <li>
          <%= link_to "Calendar", calendar_path, class: "btn hoverable block" %>
        </li>
        <li>
          <%= link_to "Exams", exams_path, class: "btn hoverable block" %>
        </li>
        <li>
          <%= link_to "Tasks", tasks_path, class: "btn hoverable block" %>
        </li>
        <% if current_user.admin_teams.any? %>
          <li>
            <%= link_to "Create task", new_task_path, class: "btn hoverable block" %>
          </li>
        <% end %>
      <% else %>
        <li>
          <%= link_to "Log in", new_user_session_path, class: "btn hoverable block" %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/layouts/_structure.html.erb
<script>
  toastr.options = {
    "closeButton": true,
    "debug": false,
    "newestOnTop": false,
    "progressBar": true,
    "positionClass": "toast-top-full-width",
    "preventDuplicates": true,
    "onclick": null,
    "showDuration": "300",
    "hideDuration": "1000",
    "timeOut": "0",
    "extendedTimeOut": "1000",
    "showEasing": "swing",
    "hideEasing": "linear",
    "showMethod": "fadeIn",
    "hideMethod": "fadeOut"
  }
    <% if notice.blank? != true %>
      toastr.info('<h5><%= notice %></h5>')
    <% end %>
</script>

<main>
  <%= yield %>
</main>
<aside>
  <%= render partial: "layouts/menu" %>
</aside>
<%= render partial: "layouts/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoGether</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="theme-color" content="#2244AA">
    <link rel="manifest" href="/manifest.json">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('icons/favicon/icon.ico') %>
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  </head>
  <body>
    <%= render partial: "layouts/structure" %>
  </body>
</html>